const menuButton=document.querySelector('.menu-toggle'),nav=document.querySelector('.main-nav');menuButton?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));menuButton.textContent=open?'×':'☰'});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuButton?.setAttribute('aria-expanded','false');if(menuButton)menuButton.textContent='☰'}));const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('visible')}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const sections=[...document.querySelectorAll('main section[id]')],links=[...document.querySelectorAll('.main-nav a')];const activeObserver=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}})},{rootMargin:'-35% 0px -55% 0px'});sections.forEach(s=>activeObserver.observe(s));
const params=new URLSearchParams(window.location.search);if(params.get('submitted')==='1'){const success=document.getElementById('form-success');if(success){success.hidden=false;success.scrollIntoView({behavior:'smooth',block:'center'})}}

// Force the restored screenshot-derived images instead of cached placeholders.
const heroImage=document.querySelector('.hero-image img');if(heroImage){heroImage.src='assets/hero.webp?v=4';heroImage.alt='Bright Palmer Lake living room with mountain views'}
const aboutImage=document.querySelector('.about-image img');if(aboutImage){aboutImage.src='assets/about-ref.webp?v=4';aboutImage.alt='Freshly cleaned bathroom counter with folded towels'}

// The wide kitchen reference is stored as compact base64 text so GitHub Pages can serve it reliably.
const kitchenImage=document.querySelector('.arrival-banner img');if(kitchenImage){fetch('assets/kitchen-banner-tiny.webp.b64?v=4').then(r=>{if(!r.ok)throw new Error('image data unavailable');return r.text()}).then(t=>{const raw=atob(t.trim()),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);kitchenImage.src=URL.createObjectURL(new Blob([bytes],{type:'image/webp'}));kitchenImage.alt='Bright modern kitchen overlooking the mountains'}).catch(()=>{kitchenImage.src='assets/hero.webp?v=4'})}